services:
  teckochecker:
    build:
      context: .
      dockerfile: Dockerfile
    image: teckochecker:latest
    container_name: teckochecker
    restart: unless-stopped

    # Port mapping for API - bind to localhost only (Caddy will proxy)
    ports:
      - "127.0.0.1:8000:8000"

    # Environment variables
    environment:
      # Database location
      - DATABASE_URL=sqlite:////data/teckochecker.db

      # API configuration
      - API_HOST=0.0.0.0
      - API_PORT=8000

      # Polling intervals (seconds)
      - DEFAULT_POLL_INTERVAL=60
      - RETRY_DELAY=300

      # Encryption key - MUST be set
      # Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
      - SECRET_KEY=${SECRET_KEY:?SECRET_KEY is required}

    # Persistent volumes
    volumes:
      # Database persistence
      - teckochecker-data:/data

      # Optional: Mount .env file for additional configuration
      # - ./.env:/app/.env:ro

    # Health check
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Resource limits (optional, adjust as needed)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  # Optional: Debug variant with shell access
  teckochecker-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: teckochecker:debug
    container_name: teckochecker-debug
    restart: "no"
    profiles:
      - debug

    ports:
      - "8000:8000"

    environment:
      - DATABASE_URL=sqlite:////data/teckochecker.db
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEFAULT_POLL_INTERVAL=60
      - RETRY_DELAY=300
      - SECRET_KEY=${SECRET_KEY:?SECRET_KEY is required}

    volumes:
      - teckochecker-data:/data

    # Override entrypoint for debugging
    entrypoint: ["/busybox/sh"]
    command: []

  # Caddy reverse proxy with HTTPS only (no port 80)
  caddy:
    image: caddy:2-alpine
    container_name: teckochecker-caddy
    restart: unless-stopped

    ports:
      - "443:443"    # HTTPS only
      - "443:443/udp" # HTTP/3

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

    depends_on:
      - teckochecker

    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  teckochecker-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local
